"""add auto_book to scan

Revision ID: 58ddbce58871
Revises: 1630918bdc90
Create Date: 2026-07-01 23:09:26.040258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ddbce58871'
down_revision: Union[str, None] = '1630918bdc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scans',
        sa.Column('auto_book', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'auto_book')
    # ### end Alembic commands ###
