"""add equipment_types to scan

Revision ID: cd380ad68ddb
Revises: 3949973585e2
Create Date: 2026-09-20 23:35:32.962297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd380ad68ddb'
down_revision: Union[str, None] = '3949973585e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('equipment_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'equipment_types')
    # ### end Alembic commands ###
