"""initial

Revision ID: d4b57c9112f7
Revises: 
Create Date: 2026-05-13 01:12:42.271743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b57c9112f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('recreationgov_email', sa.String(), nullable=True),
    sa.Column('recreationgov_password', sa.String(length=256), nullable=True, comment='Fernet-encrypted; key in ENCRYPTION_KEY env'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', name='scanstatus', native_enum=False), nullable=False),
    sa.Column('polling_interval', sa.Integer(), nullable=False),
    sa.Column('rec_area_ids', sa.JSON(), nullable=True),
    sa.Column('campground_ids', sa.JSON(), nullable=True),
    sa.Column('campsite_ids', sa.JSON(), nullable=True),
    sa.Column('search_windows', sa.JSON(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('weekends_only', sa.Boolean(), nullable=False),
    sa.Column('notify_via_email', sa.Boolean(), nullable=False),
    sa.Column('notify_via_telegram', sa.Boolean(), nullable=False),
    sa.Column('notify_on_new_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('success', 'no_results', 'error', name='scanoutcome', native_enum=False), nullable=True),
    sa.Column('sites_found', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_scan_id'), 'scan_runs', ['scan_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('campsite_id', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('campsite_type', sa.String(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_end_date', sa.Date(), nullable=False),
    sa.Column('booking_url', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cart_added', sa.Boolean(), nullable=False),
    sa.Column('cart_added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_results_dedup', 'scan_results', ['scan_id', 'campsite_id', 'booking_date'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_run_id'), 'scan_results', ['scan_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_results_scan_run_id'), table_name='scan_results')
    op.drop_index('ix_scan_results_dedup', table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_scan_runs_scan_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('users')
    # ### end Alembic commands ###
