"""add facility and area identifiers to scan_results

Revision ID: f8c666bac4cb
Revises: 3428da47a524
Create Date: 2026-07-21 14:53:27.612299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c666bac4cb'
down_revision: Union[str, None] = '3428da47a524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('facility_id', sa.String(), nullable=True))
    op.add_column('scan_results', sa.Column('recreation_area_id', sa.String(), nullable=True))
    op.add_column('scan_results', sa.Column('recreation_area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_results', 'recreation_area')
    op.drop_column('scan_results', 'recreation_area_id')
    op.drop_column('scan_results', 'facility_id')
    # ### end Alembic commands ###
